import 'package:flutter/material.dart';

final ValueNotifier<String> localeNotifier = ValueNotifier('rw');

class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'nav_home': 'Home',
      'nav_bible': 'Bible',
      'nav_hymns': 'Hymns',
      'nav_saved': 'Saved',
      
      // Settings Screen
      'settings_title': 'Settings',
      'settings_account': 'Google Account',
      'settings_signin': 'Sign In with Google',
      'settings_signout': 'Sign Out',
      'settings_sync': 'Data Sync',
      'settings_backup': 'Back Up Now',
      'settings_restore': 'Restore Backup',
      'settings_privacy': 'Privacy Policy',
      'settings_language': 'Language',
      'settings_select_lang': 'Select Language',
      'settings_account_desc': 'Sign in to automatically sync your reading history, playlists, highlights, and notes securely to Google Drive.',
      'settings_sync_desc': 'Your data is backed up securely to your hidden personal App Data folder on Google Drive.',
      'settings_sync_loading': 'Syncing data...',
      'settings_backup_success': 'Data backed up successfully!',
      'settings_backup_failed': 'Backup failed. Please check your connection.',
      'settings_restore_success': 'Data restored successfully! Please restart the app to apply all settings.',
      'settings_restore_failed': 'Restore failed. No backup file found.',
      'hymns_books_title': 'Hymn Books',
      'hymns_search_hint': 'Search hymns (title, number, lyrics)...',
      'reader_settings_font_size': 'Font Size',
      'reader_settings_theme': 'Reading Theme',
      'reader_settings_theme_white': 'White',
      'reader_settings_theme_warm': 'Warm',
      'reader_settings_theme_black': 'Black',
      'reader_settings_translation': 'Translation',
      'toast_verse_copied': 'Verse copied successfully!',
      'toast_sleep_timer_fired': 'Reading stopped (Sleep Timer fired).',
      'toast_sleep_timer_set': 'Reading will stop after {minutes} minutes!',
      'settings_restore_confirm_title': 'Restore Data?',
      'settings_restore_confirm_desc': 'This will overwrite your current local data (playlists, highlights, notes) with the backup from Google Drive. Do you want to proceed?',
      'settings_cancel': 'Cancel',
      'settings_restore_btn': 'Restore',
      'settings_restart_title': 'Restart Required',
      'settings_restart_desc': 'Restore completed! Please restart the application to apply all settings properly.',
      'settings_signed_in_as': 'Signed in as',
      'settings_signed_out': 'Signed out successfully.',

      // Dashboard
      'dash_welcome': 'Welcome',
      'dash_stats': 'Devotion Stats',
      'dash_streak': 'Streak Days',
      'dash_chapters': 'Chapters Read',
      'dash_hymns': 'Hymns Sung',
      'dash_verse_of_day': 'Verse of the Day',
      'dash_prayer_of_day': 'Daily Devotion',
      'dash_prayer': 'Prayer',
      'dash_explanation': 'Explanation',
      'dash_devotion_content': 'Devotion Content',

      // Bible Reader
      'bible_search': 'Search Bible verses...',
      'bible_sleep_timer': 'Sleep Timer',
      'bible_minutes': 'minutes',
      'bible_font_settings': 'Font Settings',
      'bible_font_size': 'Font Size',
      'bible_speech_speed': 'Speech Speed',
      'bible_translation': 'Translation',
      'bible_highlight': 'Highlight',
      'bible_add_note': 'Add Note',
      'bible_copy': 'Copy',
      'bible_share': 'Share',
      'bible_add_playlist': 'Add to Playlist',
      'bible_timer_set': 'Timer set for',
      'bible_timer_cancelled': 'Timer cancelled',
      'bible_timer_expired': 'Sleep timer expired. Audio stopped.',

      // Hymns Screen
      'hymns_search': 'Search hymns...',
      'hymns_my_playlists': 'My Playlists',
      'hymns_all_hymns': 'All Hymns',
      'hymns_create_playlist': 'Create Playlist',
      'hymns_playlist_name': 'Playlist Name',
      'hymns_save': 'Save',
      'hymns_add_to': 'Add to Playlist',

      // Saved Items Screen
      'saved_verses': 'Favorite Verses',
      'saved_notes': 'My Notes',
      'saved_highlights': 'Highlights',
      'saved_playlists': 'Hymn Playlists',
      'saved_no_items': 'No items saved yet.',
      
      // Additional keys
      'theme_light_mode': 'Light Theme',
      'theme_dark_mode': 'Dark Theme',
      'verse_copied': 'Verse copied!',
      'dash_recently_read': 'Recently Read',
      'dash_categories': 'Explore Gospel Hub',
      'dash_bible_desc': 'Old and New Testaments / Biblia Yera & KJV',
      'dash_hymns_title': 'Hymns of Praise & Salvation',
      'dash_hymns_desc': 'Christian hymns and songs of faith',
      'dash_saved_desc': 'Access your bookmarks, highlights, and playlists',
      'saved_tab_verses': 'Verses',
      'saved_tab_hymns': 'Hymns',
      'saved_tab_study': 'Study',
      'saved_empty_verses': 'No favorite verses saved yet.',
      'saved_empty_hymns': 'No favorite hymns saved yet.',
      'saved_empty_study': 'No study notes or highlights saved yet.',
      'saved_empty_tag': 'No verses for this tag.',
    },
    'rw': {
      'nav_home': 'Ahabanza',
      'nav_bible': 'Bibiliya',
      'nav_hymns': 'Indirimbo',
      'nav_saved': 'Ibibitswe',

      // Settings Screen
      'settings_title': 'Iparametre',
      'settings_account': 'Konti ya Google',
      'settings_signin': 'Injira na Google',
      'settings_signout': 'Sohoka',
      'settings_sync': 'Kubika no Kurura',
      'settings_backup': 'Bika Ibyo Wasomye',
      'settings_restore': 'Garura Ibyabitswe',
      'settings_privacy': 'Amategeko y\'Ibwanga',
      'settings_language': 'Ururimi',
      'settings_select_lang': 'Hitamo Ururimi',
      'settings_account_desc': 'Injira na Google kugira ngo ubike mu buryo bwikora amakuru wasomye, playlists, n\'inoti zawe neza kuri Google Drive.',
      'settings_sync_desc': 'Amakuru yawe abikwa mu buryo bwizewe mu bubiko bwawe bwite bwa Google Drive (Hidden App Folder).',
      'settings_sync_loading': 'Tugiye kubika/kurura...',
      'settings_backup_success': 'Ibyabitswe byabitswe muri Google Drive neza!',
      'settings_backup_failed': 'Kubika byanze. Reba connection yawe.',
      'settings_restore_success': 'Ibintu byose byagarutse neza! Siga ufungure porogaramu bundi bushya.',
      'settings_restore_failed': 'Ntibyakunze kururwa. Nta backup yabonetse.',
      'hymns_books_title': 'Ibitabo by\'Indirimbo',
      'hymns_search_hint': 'Shaka indirimbo (izina, numero cyangwa amagambo)...',
      'reader_settings_font_size': 'Ibipimo by\'Inyandiko',
      'reader_settings_theme': 'Ibikoresho by\'Umwanya',
      'reader_settings_theme_white': 'Umweru',
      'reader_settings_theme_warm': 'Umutuku',
      'reader_settings_theme_black': 'Umukara',
      'reader_settings_translation': 'Umuhinduzi (Translation)',
      'toast_verse_copied': 'Umusaruro wakopijwe!',
      'toast_sleep_timer_fired': 'Gusoma guhagaze kuko igihe cyarangiye (Sleep Timer fired).',
      'toast_sleep_timer_set': 'Gusoma bizahagarara nyuma y\'iminota {minutes}!',
      'settings_restore_confirm_title': 'Kurura Ibyabitswe?',
      'settings_restore_confirm_desc': 'Ibi bigiye gusimbura amakuru yose ari kuri terefone n\'ayabitswe muri Google Drive. Urabyemeza?',
      'settings_cancel': 'Reka',
      'settings_restore_btn': 'Yego',
      'settings_restart_title': 'Gusubiramo App',
      'settings_restart_desc': 'Kurura byagenze neza! Kugira ngo ibikururwa byose byinjire neza, fungura app bundi bushya.',
      'settings_signed_in_as': 'Winjiye nka',
      'settings_signed_out': 'Wamaze gusohoka neza.',

      // Dashboard
      'dash_welcome': 'Murakaza neza',
      'dash_stats': 'Imibare y\'Ibyo Wasomye',
      'dash_streak': 'Iminsi Ikurikirana',
      'dash_chapters': 'Ibice Wasomye',
      'dash_hymns': 'Indirimbo Waririmbye',
      'dash_verse_of_day': 'Ijambo ry\'Uyu Munsi',
      'dash_prayer_of_day': 'Isengesho ry\'Uyu Munsi',
      'dash_prayer': 'Isengesho',
      'dash_explanation': 'Igisobanuro',
      'dash_devotion_content': 'Ibikubiyemo',

      // Bible Reader
      'bible_search': 'Shakisha umurongo...',
      'bible_sleep_timer': 'Guhagarika (Timer)',
      'bible_minutes': 'munsi',
      'bible_font_settings': 'Guhindura Ibyanditswe',
      'bible_font_size': 'Ingano',
      'bible_speech_speed': 'Umuvuduko',
      'bible_translation': 'Umuhinduzi',
      'bible_highlight': 'Gushimusha',
      'bible_add_note': 'Kwandika Inyote',
      'bible_copy': 'Gukoporora',
      'bible_share': 'Gusangiza',
      'bible_add_playlist': 'Shyira muri Playlist',
      'bible_timer_set': 'Guhagarika gushyizwe kuri',
      'bible_timer_cancelled': 'Guhagarika gahagaritswe',
      'bible_timer_expired': 'Igihe cyo guhagarika cyageze. Ijwi rihagaze.',

      // Hymns Screen
      'hymns_search': 'Shakisha indirimbo...',
      'hymns_my_playlists': 'Izanjye',
      'hymns_all_hymns': 'Zose',
      'hymns_create_playlist': 'Crea Playlist',
      'hymns_playlist_name': 'Izina rya Playlist',
      'hymns_save': 'Bika',
      'hymns_add_to': 'Shyira muri Playlist',

      // Saved Items Screen
      'saved_verses': 'Imirongo Yasomwe',
      'saved_notes': 'Notes Zanjye',
      'saved_highlights': 'Highlights',
      'saved_playlists': 'Playlists z\'Indirimbo',
      'saved_no_items': 'Nta kintu kirabikwa.',
      
      // Additional keys
      'theme_light_mode': 'Koresha umweru',
      'theme_dark_mode': 'Koresha umukara',
      'verse_copied': 'Umurongo wakopijwe!',
      'dash_recently_read': 'Aho ugeze usoma',
      'dash_categories': 'Ibice by\'Ijambo',
      'dash_bible_desc': 'Isezerano rya Kera n\'Iryo Kabiri mu Kinyarwanda',
      'dash_hymns_title': 'Indirimbo zo Gushimisha n\'Agakiza',
      'dash_hymns_desc': 'Indirimbo z\'Agakiza n\'iz\'Imana zo Gushimisha',
      'dash_saved_desc': 'Gushaka imirongo n\'indirimbo wabitse',
      'saved_tab_verses': 'Imirongo',
      'saved_tab_hymns': 'Indirimbo',
      'saved_tab_study': 'Icyigisho',
      'saved_empty_verses': 'Nta murongo w\'Ijambo watoranyijwe urabikwa.',
      'saved_empty_hymns': 'Nta ndirimbo yatoranyijwe urabikwa.',
      'saved_empty_study': 'Nta nyandiko cyangwa bimurikirwa bikabikwa.',
      'saved_empty_tag': 'Nta mirongo ifite iki kimenyetso.',
    }
  };

  static String translate(String key) {
    final lang = localeNotifier.value;
    return _localizedValues[lang]?[key] ?? key;
  }
}
